Repository FRONTENDSCHOOL6/Lionly, pull requests merged in 2023-09, with the labels that each got.

#11 [PR] README 및 CODEOWNERS 추가
  .github/CODEOWNERS
  README.md
Labels: Ask, PR

#12 [Chore] 개발 환경 구성
  .eslintrc.cjs
  jsconfig.json
  tailwind.config.js
  vite.config.js
Labels: Ask, Environment

#13 [PR] 파비콘, 로고 추가 | svgr 플러그인 설치 | 절대경로 설정 추가 | 기본 폰트 설정 | tailwind.config 수정
  .eslintrc.cjs
  .github/CODEOWNERS
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/vite.svg
  src/App.jsx
  src/assets/lionHeadLogo_common.svg
  src/assets/lionLogo_common.svg
  src/index.css
  tailwind.config.js
  vite.config.js
Labels: Ask, Design, PR, Environment

#18 [PR] 리드미 수정 및 파비콘 로드 경로 수정
  README.md
  index.html
Labels: Ask, Refactoring, Document, PR

#20 [PR] 프로필 변경 버튼 컴포넌트, 채널 변경 버튼 컴포넌트 구현
  jsconfig.json
  src/App.jsx
  src/assets/camera_myProfile.svg
  src/assets/profilePencil_myProfile.svg
  src/components/Button/ChannelButtonList.jsx
  src/components/Button/InsertProfileButton.jsx
  src/components/Button/ProfileImage.jsx
  src/contexts/Channel.jsx
  src/contexts/ProfileImage.jsx
  src/hooks/useChannel.js
  src/hooks/useProfileImage.js
  src/main.jsx
  src/utils/getNodeIndex.js
  src/utils/index.js
  vite.config.js
Labels: Ask, Feature, Design, Component, PR

#21 Feed
  package-lock.json
  src/App.jsx
  src/assets/KebabMenuButton_FeedList.svg
  src/hooks/useFetchData.js
  src/pages/FeedList.jsx
  src/pages/Home.jsx
  src/utils/getPbImageURL.js
Labels: PR

#22 Develop
  src/App.jsx
  src/components/input/FormInput.jsx
  src/components/input/NicknameInput.jsx
  src/utils/validation.js
Labels: Ask, Feature, Component, PR

#25 [Docs] Issue 템플릿 생성 (에러 또는 버그 발생 시)
  .github/ISSUE_TEMPLATE/버그-또는-에러-발생-시.md
Labels: Ask, PR

#26 [PR] 채널 변경 버튼 컴포넌트 키보드 이동 기능(함수) 추가 및 스피너 컴포넌트 틀 추가
  src/assets/react.svg
  src/components/Button/ChannelButtonList.jsx
  src/components/Spinner.jsx
  src/utils/handleTabArrowControl.js
Labels: Enhance, Ask, Feature, Component, PR

#27 [PR] 로딩 스피너 구성 완료
  src/components/Button/ChangeButton.jsx
  src/components/Button/LogoutButton.jsx
  src/components/Spinner.jsx
  src/contexts/Channel.jsx
Labels: Discuss, Ask, Design, Component, PR

#28 Button
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/assets/feed_Header.svg
  src/assets/pen_Writing.svg
  src/components/Button/WritingButton.jsx
  src/components/layout/FeedHeader.jsx
  src/main.jsx
  src/pages/Content.jsx
  src/pages/Error-page.jsx
  src/pages/Feed.jsx
  src/pages/Landing.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/Writing.jsx
  src/routes.jsx
Labels: Ask, PR, Environment

#29 Develop
  src/App.jsx
  src/components/input/FormInput.jsx
  src/utils/maxLengthCheck.js
Labels: Ask, Feature, Component, PR

#31 Feed
  src/components/layout/FeedList.jsx
  src/hooks/useFeedList.js
  src/pages/FeedList.jsx
  src/pages/Home.jsx
Labels: PR

#46 [PR] 프로필 이미지 아이콘 및 채널 변경 탭 보완
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/api/getChannelList.js
  src/api/getProfileImageURL.js
  src/api/pocketbase.js
  src/components/Button/BigButton.jsx
  src/components/Button/ChannelButtonList.jsx
  src/components/Button/ChannelTab.jsx
  src/components/Button/StartButton.jsx
  src/components/MainLogo.jsx
  src/components/SmallLogo.jsx
  src/components/layout/BeforeLogin.jsx
  src/components/layout/RootLayout.jsx
  src/contexts/Channel.jsx
  src/contexts/ProfileImage.jsx
  src/hooks/useChannel.js
  src/hooks/useTitle.js
  src/main.jsx
  src/pages/Content.jsx
  src/pages/ErrorPage.jsx
  src/pages/Feed.jsx
  src/pages/Landing.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/Writing.jsx
  src/pages/index.js
  src/routes.jsx
  src/utils/index.js
Labels: Enhance, Ask, Feature, Component, PR

#51 [PR] `feeds` collection에서 `expand`를 통해 `users`의 `profile_image`와 `nickname` 불러오기
  .gitignore
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/api/pocketbase.js
  src/components/layout/FeedHeader.jsx
  src/components/layout/FeedList.jsx
  src/pages/Landing.jsx
Labels: Feature, PR

#52 Develop
  pnpm-lock.yaml
  src/App.jsx
  src/api/getFeedText.js
  src/components/Button/BigButton.jsx
  src/components/input/FormInput.jsx
  src/components/layout/BeforeLogin.jsx
  src/components/layout/FeedList.jsx
  src/components/layout/RootLayout.jsx
  src/pages/SignUp.jsx
Labels: Component, PR, Environment

#53 [PR]feeds collection에서 expand를 통해 users의 profile_image와 nickname 불러오기 수정
  pnpm-lock.yaml
  src/App.jsx
  src/api/getFeedList.js
  src/components/layout/FeedList.jsx
Labels: PR

#54 [PR] 공통 레이아웃 수정, BigButton 컴포넌트 수정, 에러 페이지 디자인 추가
  src/api/getProfileNickname.js
  src/components/Button/BigButton.jsx
  src/components/Button/ChannelTab.jsx
  src/components/Button/InsertProfileButton.jsx
  src/components/Button/ProfileImage.jsx
  src/components/Button/WritingButton.jsx
  src/components/Button/index.js
  src/components/MainLogo.jsx
  src/components/layout/BeforeLogin.jsx
  src/components/layout/FeedHeader.jsx
  src/components/layout/RootLayout.jsx
  src/contexts/ProfileImage.jsx
  src/hooks/useTitle.js
  src/pages/ErrorPage.jsx
  src/pages/Feed.jsx
  src/pages/Landing.jsx
  src/routes.jsx
Labels: Enhance, Ask, Fix, Refactoring, Design, Component, PR

#57 [PR] 회원가입 페이지 스타일 변경
  pnpm-lock.yaml
  src/components/Button/BigButton.jsx
  src/components/input/FormInput.jsx
  src/pages/SignUp.jsx
Labels: Enhance, Design, Component, PR

#58 [3차 작업] 기능 구현을 포함한 로그인 페이지 구현하기, 로그아웃 버튼 기능 구현하기
  src/App.jsx
  src/api/useFeedHeader.js
  src/components/Button/FindAcountButton.jsx
  src/components/Button/LinkButton.jsx
  src/components/Button/LogoutButton.jsx
  src/components/Button/index.js
  src/components/layout/Login.jsx
  src/contexts/AuthProvider.jsx
  src/hooks/useStorageData.js
  src/pages/Landing.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: Ask, Feature, Component, PR

#59 [PR] 회원가입 input 중복값 처리 및 유효성 검사에 따른 회원가입 제한 및 toast 알림 구현 완료
  src/App.jsx
  src/api/createUserInfo.js
  src/components/input/FormInput.jsx
  src/pages/SignUp.jsx
Labels: Feature, Design, PR

#60 [PR] 피드 페이지 구현
  index.html
  src/App.jsx
  src/api/getFeedList.js
  src/api/getProfileImageURL.js
  src/api/getProfileNickname.js
  src/assets/arrow_Feed_down.svg
  src/assets/arrow_Feed_up.svg
  src/assets/profileEdit_Feed.svg
  src/components/Button/ChannelTab.jsx
  src/components/Button/InsertProfileButton.jsx
  src/components/Button/LogoutButton.jsx
  src/components/Button/ProfileImage.jsx
  src/components/Button/WritingButton.jsx
  src/components/MainLogo.jsx
  src/components/SmallLogo.jsx
  src/components/Spinner.jsx
  src/components/layout/FeedHeader.jsx
  src/components/layout/FeedList.jsx
  src/components/layout/RootLayout.jsx
  src/contexts/Channel.jsx
  src/contexts/ProfileImage.jsx
  src/hooks/useFeed.js
  src/hooks/useFeedList.js
  src/hooks/useStorageData.js
  src/pages/ErrorPage.jsx
  src/pages/Feed.jsx
  src/pages/Landing.jsx
  src/routes.jsx
  src/utils/getDate.js
  src/utils/index.js
  src/utils/moveScrollTop.js
Labels: Ask, Feature, Design, Component, PR

#61 3차 작업물 애니메이션 추가 및 코드 수정
  src/App.jsx
  src/components/Button/FindAcountButton.jsx
  src/components/layout/Login.jsx
  src/contexts/AuthProvider.jsx
Labels: Ask, Feature, PR

#62 routes 구조 변경 , useStorageData if 문제거 ,
  src/components/ProtecteRoute.jsx
  src/hooks/useStorageData.js
  src/routes.jsx
Labels: Ask, Fix, Feature, PR

#63 [PR] React.memo 설정, 기본 프로필 이미지 설정, ProfileImage Context 삭제
  src/App.jsx
  src/components/Button/ChannelTab.jsx
  src/components/Button/InsertProfileButton.jsx
  src/components/Button/ProfileImage.jsx
  src/components/Button/index.js
  src/components/layout/FeedHeader.jsx
  src/components/layout/FeedList.jsx
  src/contexts/ProfileImage.jsx
  src/hooks/useFeed.js
  src/hooks/useProfileImage.js
  src/hooks/useStorageData.js
  src/pages/Feed.jsx
Labels: Enhance, Ask, Refactoring, Component, PR

#65 [PR] vercel 배포 환경 구성 및 route 구성 등
  src/api/pocketbase.js
  src/assets/kebabMenuButton_FeedList.svg
  src/components/Button/FindAcountButton.jsx
  src/components/ChannelTab.jsx
  src/components/button/ChangeButton.jsx
  src/components/button/FindAccountButton.jsx
  src/components/button/LinkButton.jsx
  src/components/button/LogoutButton.jsx
  src/components/button/ProfileImage.jsx
  src/components/button/WritingButton.jsx
  src/components/button/index.js
  src/components/layout/FeedList.jsx
  src/components/layout/Login.jsx
  src/pages/Edit.jsx
  src/pages/Feed.jsx
  src/pages/SignUp.jsx
  src/routes.jsx
  src/utils/getImageData.js
  src/utils/getPbImageURL.js
  vercel.json
Labels: Discuss, Ask, Component, PR, Environment

#70 [PR] Feed 페이지 관련 14개 파일 수정
  src/components/ChannelTab.jsx
  src/components/button/LogoutButton.jsx
  src/components/button/ProfileImage.jsx
  src/components/layout/FeedHeader.jsx
  src/components/layout/FeedList.jsx
  src/contexts/Channel.jsx
  src/hooks/index.js
  src/hooks/useInfiniteFeed.js
  src/hooks/useObserveScroll.js
  src/pages/Feed.jsx
  src/routes.jsx
  src/utils/index.js
  src/utils/moveScrollTop.js
  src/utils/onLoadMoveScrollTop.js
Labels: Enhance, Ask, Fix, Refactoring, Feature, Component, PR

#71 [PR] Feed 페이지 스크롤 이벤트 버그 수정 및 Content 페이지 일부 구현
  index.html
  src/api/getFeed.js
  src/assets/arrow_common_left.svg
  src/components/layout/FeedList.jsx
  src/hooks/index.js
  src/hooks/useFeed.js
  src/hooks/useInfiniteFeed.js
  src/hooks/useObserveScroll.js
  src/hooks/useScroll.js
  src/pages/Content.jsx
  src/pages/Feed.jsx
  src/routes.jsx
  src/utils/getPbImageURL.js
  src/utils/index.js
Labels: Enhance, Ask, Fix, Refactoring, Feature, Design, Component, PR

#72 [PR] Feed 페이지 마크업 요소 수정 및 Content 페이지 댓글 창 일부 구현
  src/api/getFeed.js
  src/api/getFeedList.js
  src/components/ChannelTab.jsx
  src/components/layout/FeedHeader.jsx
  src/components/layout/FeedList.jsx
  src/hooks/index.js
  src/hooks/useContent.js
  src/hooks/useScroll.js
  src/pages/Content.jsx
  src/utils/getPbImageURL.js
  src/utils/getTimeDifference.js
  src/utils/index.js
Labels: Ask, Fix, Refactoring, Feature, Component, PR

#73 [PR] Content 페이지 기본 기능 구현
  src/api/createComment.js
  src/api/updateComment.js
  src/components/button/ProfileImage.jsx
  src/components/content/Comments.jsx
  src/components/content/Content.jsx
  src/components/content/Header.jsx
  src/components/content/WriteComment.jsx
  src/components/content/index.js
  src/components/layout/FeedHeader.jsx
  src/hooks/useComments.js
  src/hooks/useContent.js
  src/hooks/useObserveScroll.js
  src/pages/Content.jsx
  src/pages/Contents.jsx
  src/pages/Feed.jsx
  src/pages/index.js
  src/routes.jsx
  src/utils/calcTimeDifference.js
  src/utils/index.js
  src/utils/onLoadMoveScrollTop.js
Labels: Refactoring, Feature, Design, Component, PR

#74 [PR] 글쓰기 페이지 기능 구현 및 회원가입 페이지 유효성 검사 코드 수정/ framer-motion 추가
  src/App.jsx
  src/api/createFeedData.js
  src/api/createUserInfo.js
  src/assets/check.svg
  src/assets/leftarrow.svg
  src/assets/pencil.svg
  src/assets/plus.svg
  src/hooks/useTextarea.js
  src/hooks/useUploadImage.js
  src/pages/SignUp.jsx
  src/pages/Writing.jsx
Labels: Enhance, Refactoring, Feature, Design, PR

#75 [PR] 마이페이지 추가 기능 (프로필 편집 모달창 및 글 수정/삭제 드롭다운 메뉴)
  pnpm-lock.yaml
  src/api/deleteMyFeed.js
  src/api/getMyFeedList.js
  src/api/getProfileEmail.js
  src/assets/buttonPrev_MyPage.svg
  src/assets/delete_Feed.svg
  src/assets/signOut_MyPage.svg
  src/components/content/Header.jsx
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/components/layout/ProfileEdit.jsx
  src/hooks/useDropDown.js
  src/hooks/useInfiniteMyFeed.js
  src/pages/MyPage.jsx
Labels: Ask, Feature, PR

#76 [4차 작업] 수정하기 페이지 만들기 및 기능 구현
  README.md
  src/assets/PlusButton_Writing.svg
  src/components/layout/Login.jsx
  src/components/layout/MyFeedList.jsx
  src/hooks/useStorageData.js
  src/pages/Edit.jsx
  src/pages/SignIn.jsx
  src/routes.jsx
Labels: Ask, Feature, Component, PR

#77 [PR] 글쓰기 페이지 자동 리로드 및 알림창 설정
  src/pages/Writing.jsx
Labels: Enhance, Feature, PR

#78 [PR] 댓글에 답글달기 기능 구현 (디자인 미완성)
  src/App.jsx
  src/api/createComment.js
  src/api/getContent.js
  src/api/getFeed.js
  src/api/updateComment.js
  src/components/button/ProfileImage.jsx
  src/components/content/Comments.jsx
  src/components/content/Content.jsx
  src/components/content/Header.jsx
  src/components/content/InsertComment.jsx
  src/components/content/ModalReply.jsx
  src/components/content/index.js
  src/components/layout/FeedList.jsx
  src/contexts/Reply.jsx
  src/hooks/index.js
  src/hooks/useComments.js
  src/hooks/useContent.js
  src/hooks/useFeed.js
  src/hooks/useReply.js
  src/pages/Contents.jsx
  src/routes.jsx
Labels: Ask, Refactoring, Feature, Design, PR

#79 [PR]마이페이지 내에 스타일 변경 및 닉네임 유효성 검사 및 에러창 설정
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/components/layout/ProfileEdit.jsx
Labels: Enhance, Ask, Refactoring, PR

#80 [PR] 글쓰기 페이지 에러 수정 및 피드 헤더 애니메이션 구현
  src/components/layout/FeedHeader.jsx
  src/pages/Writing.jsx
Labels: Enhance, Fix, Design, PR

#81 접근성 향상 및 불필요한 코드 제거
  src/components/button/FindAccountButton.jsx
  src/components/layout/Login.jsx
  src/contexts/AuthProvider.jsx
  src/pages/Edit.jsx
  src/pages/SignIn.jsx
Labels: Enhance, Ask, PR

#83 [PR] Reply 컬렉션 포켓호스트 내에서도 데이터 삭제되도록 구현
  src/api/deleteMyFeed.js
  src/api/getMyFeedList.js
  src/components/layout/MyFeedList.jsx
Labels: Enhance, Ask, Fix, PR

#84 [PR] 마이페이지 스타일 변경
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/pages/MyPage.jsx
Labels: Enhance, Design, PR

#85 Edit 페이지 코드 수정
  src/hooks/useInfiniteMyFeed.js
  src/pages/Edit.jsx
Labels: Enhance, Ask, Refactoring, PR

#86 [PR] 접근성 고려한 코드 추가 및 refetch 추가
  src/hooks/useInfiniteFeed.js
  src/pages/SignUp.jsx
  src/pages/Writing.jsx
Labels: Enhance, Ask, Refactoring, PR

#87 [PR] 댓글 작성 버그 수정, 스크롤 버그 관련 코드 수정, 댓글 수/수정됨 표시 기능 구현
  src/App.jsx
  src/api/getFeedList.js
  src/components/layout/contents/Comments.jsx
  src/components/layout/contents/Content.jsx
  src/components/layout/contents/Header.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/components/layout/contents/WriteComment.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Channel.jsx
  src/contexts/Content.jsx
  src/contexts/Reply.jsx
  src/contexts/index.js
  src/hooks/index.js
  src/hooks/useContent.js
  src/hooks/useCreateComment.js
  src/hooks/useDeleteComment.js
  src/hooks/useInfiniteFeed.js
  src/hooks/useModal.js
  src/hooks/useReply.js
  src/hooks/useSubscribe.js
  src/pages/Contents.jsx
  src/pages/Feed.jsx
  src/routes.jsx
Labels: Enhance, Ask, Fix, Refactoring, Feature, Component, PR

#93 수정하기 페이지 마크업 수정
  src/pages/Edit.jsx
Labels: Enhance, Ask, PR

#94 [PR] 모바일 글쓰기 페이지 스타일 코드 수정
  src/pages/Writing.jsx
Labels: Enhance, Ask, Design, PR

#95 [PR] 기본 폰트 컬러 설정, routes 경로 수정, 코드 리팩토링
  src/components/button/LogoutButton.jsx
  src/components/button/WritingButton.jsx
  src/components/layout/contents/Comments.jsx
  src/components/layout/contents/Content.jsx
  src/components/layout/contents/Header.jsx
  src/components/layout/contents/InsertComment.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/components/layout/feed/ChannelTab.jsx
  src/components/layout/feed/FeedHeader.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Content.jsx
  src/hooks/useCreateComment.js
  src/hooks/useDeleteComment.js
  src/index.css
  src/pages/Contents.jsx
  src/pages/Feed.jsx
  src/routes.jsx
  src/utils/handleKeyboardArrowControl.js
Labels: Enhance, Ask, Fix, Refactoring, Design, Component, PR

#96 [PR] 마이페이지 접근성 고려 및 폰트 크기 및 간격 조정
  src/api/deleteMyFeed.js
  src/api/getProfileEmail.js
  src/components/layout/Login.jsx
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/components/layout/ProfileEdit.jsx
  src/pages/MyPage.jsx
Labels: Enhance, Ask, PR

#97 [PR] ChannelList 경로 수정
  src/components/layout/feed/ChannelTab.jsx
  src/components/layout/feed/FeedHeader.jsx
  src/components/layout/feed/FeedList.jsx
  src/routes.jsx
Labels: Ask, Fix, PR

#99 [PR] 글쓰기 페이지 접근성 개선
  src/pages/Writing.jsx
Labels: Enhance, Ask, Fix, Refactoring, PR

#100 [PR] 글쓰기 페이지 함수 추가
  src/pages/Writing.jsx
Labels: Enhance, Ask, Refactoring, PR

#101 [PR] 드롭다운 위치 수정 및 모달창 접근성 고려
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/components/layout/ProfileEdit.jsx
Labels: Enhance, Ask, PR

#102 [PR] 게시글 선택 시 전에 선택했던 게시글이 먼저 로드됐다가 바뀌는 현상 수정
  src/components/layout/contents/Comments.jsx
  src/components/layout/contents/Content.jsx
  src/components/layout/contents/Header.jsx
  src/components/layout/contents/InsertComment.jsx
  src/components/layout/feed/FeedHeader.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Content.jsx
  src/contexts/Reply.jsx
  src/hooks/useCreateComment.js
  src/hooks/useDeleteComment.js
  src/pages/Contents.jsx
  src/utils/handleKeyboardArrowControl.js
Labels: Enhance, Ask, Fix, Refactoring, Feature, Component, PR

#103 [PR] 버그 수정 테스트
  src/components/layout/MyPageHeader.jsx
  src/components/layout/contents/Comments.jsx
Labels: Ask, Fix, PR

#106 Fix 중
  src/components/layout/MyFeedList.jsx
  src/components/layout/MyPageHeader.jsx
  src/components/layout/contents/Comments.jsx
  src/components/layout/contents/Content.jsx
  src/components/layout/contents/Header.jsx
  src/components/layout/contents/InsertComment.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Content.jsx
  src/hooks/index.js
  src/hooks/useContentData.js
  src/hooks/useCreateComment.js
  src/hooks/useDeleteComment.js
  src/pages/Contents.jsx
  src/pages/Feed.jsx
Labels: Bug, Ask, Fix, PR

#107 [PR] 댓글 버그 수정
  src/components/layout/MyPageHeader.jsx
  src/components/layout/contents/Comments.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/contexts/Content.jsx
  src/hooks/useContentData.js
  src/hooks/useCreateComment.js
  src/hooks/useDeleteComment.js
  src/pages/Contents.jsx
  src/pages/Edit.jsx
  src/pages/Writing.jsx
Labels: Ask, Fix, PR

#108 [PR] 댓글 버그 수정
  src/hooks/useContentData.js
  src/hooks/useDeleteComment.js
  src/pages/Contents.jsx
Labels: Ask, Fix, PR

#109 [PR] 버튼 위치 수정 및 프로필 편집 조건 변경
  src/components/layout/ProfileEdit.jsx
Labels: Enhance, Ask, PR

#110 [PR] 배포환경 구성
  pnpm-lock.yaml
  vercel.json
Labels: Ask, PR, Environment

#112 [PR] 배포 환경 구성
  vercel.json
Labels: Ask, PR, Environment

#114 Update MyPageHeader.jsx
  src/components/layout/MyPageHeader.jsx
Labels: Ask, Fix, PR

#115 [Add] 이미지 최적화 기능 추가
  package.json
  pnpm-lock.yaml
  src/components/layout/ProfileEdit.jsx
  src/pages/Edit.jsx
  src/pages/Writing.jsx
Labels: Ask, PR, Environment

#116 [PR] lazy 설정 및 모바일 기준 이상한 스타일링 수정
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/ProtectedRoute.jsx
  src/components/button/LogoutButton.jsx
  src/components/layout/MyFeedList.jsx
  src/components/layout/ProfileEdit.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Content.jsx
  src/contexts/Reply.jsx
  src/hooks/index.js
  src/hooks/useContentData.js
  src/hooks/useCreateComment.js
  src/hooks/useFeed.js
  src/hooks/useModal.js
  src/hooks/useSubscribe.js
  src/pages/Contents.jsx
  src/pages/Edit.jsx
  src/pages/Feed.jsx
  src/pages/Writing.jsx
  src/pages/index.js
  src/routes.jsx
  src/utils/getNodeIndex.js
  src/utils/index.js
  src/utils/renderImg.js
Labels: Discuss, Enhance, Ask, Fix, Design, Component, PR

#117 [PR] 최종 배포 전 일부 수정
  src/App.jsx
  src/components/button/WritingButton.jsx
  src/pages/Contents.jsx
  src/pages/Landing.jsx
  src/pages/MyPage.jsx
Labels: Enhance, Ask, Refactoring, PR

#119 [PR] 프로필 이미지 컴포넌트 수정
  src/components/button/ProfileImage.jsx
  src/components/layout/MyFeedList.jsx
Labels: Ask, Fix, PR

#121 [PR] 게시글 작성 에러 수정 등
  index.html
  src/components/button/WritingButton.jsx
  src/components/input/FormInput.jsx
  src/components/layout/Login.jsx
  src/components/layout/ProfileEdit.jsx
  src/components/layout/contents/ReplyModal.jsx
  src/components/layout/feed/FeedHeader.jsx
  src/components/layout/feed/FeedList.jsx
  src/contexts/Channel.jsx
  src/pages/Writing.jsx
Labels: Ask, Fix, Refactoring, PR

#122 [PR] meta 태그 추가 및 리드미 작성 등
  README.md
  index.html
  public/LionlyLogo.png
  src/components/layout/MyFeedList.jsx
  src/components/layout/contents/Content.jsx
  src/components/layout/contents/Header.jsx
  src/components/layout/feed/ChannelTab.jsx
  src/pages/Feed.jsx
  src/pages/MyPage.jsx
  vite.config.js
Labels: Enhance, Ask, Refactoring, Document, PR

#129 [PR] 피드, 컨텐츠 페이지 헤딩 레벨 수정
  src/components/layout/contents/Content.jsx
  src/components/layout/feed/FeedList.jsx
  src/pages/Feed.jsx
Labels: Ask, Refactoring, PR
